config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :products
  resources :stores
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  has_one :store
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  allow_browser versions: :modern
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_products, only: [ :show, :edit, :update, :destroy ]

  def index
    @products = Product.all
  end

  def show;end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new()

    if @product.save
      redirect_to @products, notice: "Produto criado com sucesso"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @products, notice: "Produto atualizado com sucesso"
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: "Produto removido com sucesso"
  end

  private

  def set_products
    @product = Product.find(params[:product_id])
  end

  def product_params
    params.require(:product).permit(:name, :description)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_stores, only: [ :show, :edit, :update, :destroy ]

  # The customer will use this endpoint to access all the stores
  def index
    @stores = Store.all
  end

  def show;end

  # The seller will use this endpoint to create a new store
  def new
    @store = current_user.store.new
  end

  def create
    @store = current_user.store.new(store_params)

    if @store.save
      redirect_to @stores, notice: "Loja criada com sucesso"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @store.update(product_params)
      redirect_to @stores, notice: "Loja atualizado com sucesso"
    end
  end

  def destroy
    @store.destroy
    redirect_to stores_url, notice: "Loja removido com sucesso"
  end

  private

  def set_stores
    @store = Store.find(params[:store_id])
  end

  def store_params
    params.require(:store).permit(:name, :description, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tcc" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <style>
    html, body {
      height: 100%;
    }
  </style>

  <body class="d-flex flex-column w-100 h-100 p-0 m-0">
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Início</a>
        <a class="navbar-brand" href="#">Teste</a>
        <a class="navbar-brand" href="#">Teste</a>
        <a class="navbar-brand" href="#">Teste</a>
      </div>
    </nav>
    <%= yield %>
  </body>

</html>

app/views/products/_form.html.erb
<%= form_with model: [current_user.store, @product], local: true, class: "form-horizontal" do |form| %>
    
    <!-- Product Name -->
    <div class="form-group row">
      <%= form.label :name, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :name, class: "form-control", placeholder: "Enter product name" %>
      </div>
    </div>
    
    <!-- Product Description -->
    <div class="form-group row">
      <%= form.label :description, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_area :description, class: "form-control", rows: 5, placeholder: "Enter product description" %>
      </div>
    </div>
    
    <!-- Product Price -->
    <div class="form-group row">
      <%= form.label :price, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.number_field :price, step: 0.01, class: "form-control", placeholder: "Enter product price" %>
      </div>
    </div>
    
    <!-- Submit Button -->
    <div class="form-group row">
      <div class="col-sm-10 offset-sm-2">
        <%= form.submit "Create Product", class: "btn btn-primary" %>
      </div>
    </div>

<% end %>

app/views/products/_product.html.erb
<div class="col-md-4 mb-4">
  <div class="card">
    <img src="<%= product.image_url %>" class="card-img-top" alt="<%= product.name %>">
    <div class="card-body">
      <h5 class="card-title"><%= product.name %></h5>
      <p class="card-text"><%= product.description.truncate(100) %></p>
      <p class="card-text text-muted">Price: <%= number_to_currency(product.price) %></p>
      <a href="<%= product_path(product) %>" class="btn btn-primary">View Details</a>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <h1 class="my-4">Bem Vindo(a) a nossa plataforma</h1>
  
  <div class="row">
    <%= render @products %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <h1 class="my-4">Add New Product</h1>
  
  <%= render "form", post: @product %>
</div>